#!/bin/bash

current="$(pwd)"

if [ -d "$1" ]
then
	echo "Preparing..."
else
	echo "Directory not exists: $1"
	exit 1
fi

for file in "$current"/*; do

   if [ "${file##*.}" = "mp3" -o "${file##*.}" = "wav" ]; then
   	
   	name=`echo "$file" | sed -e "s/.*\///"`
   	name=`echo "$name" | sed -e "s/.mp3$//g"`
   	name=`echo "$name" | sed -e "s/.wav$//g"`

   	echo "INPUT: $file"
   	echo "OUTPUT: $1/$name.mp3"

 			ffmpeg -i "$file" -vn -ar 44100 -ac 2 -ab 128k -f mp3 "$1/$name.mp3"
			fi

done