#!/bin/bash

current="$(pwd)"
append="/compact"
directory=$current$append
folder=0
delete=0
replace=0
only=0

function _help
{
	echo "Instruções:"
	echo "	-d | --delete	Deleta os arquivos originais após a conversão"
	echo "	-f | --folder	Define a pasta de destino dos arquivos (deve ser enviada como parâmetro o caminho da pasta)"
	echo "	-r | --replace	Substitui os arquivos originais pelos arquivos convertidos"
	echo "	-o | --only	Mantém somente os arquivos convertido. Obs: só tem efeito junto com o parâmetro '-r'."
	echo "	-h | --help	Exibe as instruções disponíveis"
}

while [[ "$1" != "" ]]; do
	case $1 in
		-d | --delete )
			delete=1
			shift
			;;
		-f | --folder )
			folder=1
			shift
			
			directory="$1"
			if [ -d "$directory" ]
			then
			   echo "Diretório encontrado."
			else
			   echo "Diretório não existe ou não foi enviado ($directory)"
			   exit 1
			fi
			shift
			;;
		-r | --replace )
			replace=1
			shift
			;;
		-o | --only )
			only=1
			shift
			;;
		-h | --help )
			shift
			_help
			exit
			;;
		* )
			echo "Comando '$1' desconhecido. Use '-h' para ver a lista de comandos."
			exit 
			;;
	esac
done

if [[ $folder = 0 ]]; then
	mkdir "$directory" || exit $?
fi

echo "####   Iniciando conversão dos arquivos   ####"

for file in "$current"/*; do

   	if [ "${file##*.}" = "mp3" -o "${file##*.}" = "wav" -o "${file##*.}" = "MP3" ]; then
      
		name=`echo "$file" | sed -e "s/.*\///"`
		name=`echo "$name" | sed -e "s/.mp3$//g"`
		name=`echo "$name" | sed -e "s/.wav$//g"`
		name=`echo "$name" | sed -e "s/.MP3$//g"`

		echo "---------------------------------------------------------------------"
		echo "INPUT: $file"
		echo "OUTPUT: $directory/$name.mp3"
		echo "Convertendo..."
        ffmpeg -loglevel panic -i "$file" -vn -ar 44100 -ac 2 -ab 128k -f mp3 "$directory/$name.mp3"
   		
   		status=$?
   		if [[ $status = 0 ]]; then 
   			if [[ $delete = 1 || $replace = 1 ]]; then
	   			rm "$file"
	   			if [[ $replace = 1 ]]; then
	   				cp "$directory/$name.mp3" "$current/$name.mp3"
	   			fi
   			fi
   			echo "Convertido"
   		else
   			echo "Houve um erro ao converter '$name.mp3'."
   		fi

   	fi

done

echo "---------------------------------------------------------------------"

if [[ $replace = 1 && $only = 1 ]]; then
	rm -rf "$directory"
fi

echo "####   Finalizado   ####"
exit