#!/bin/bash

current="$(pwd)"
append="/compact"
directory=$current$append
folder=0
delete=0
replace=0
only=0

function _help
{
	echo "Instructions:"
	echo "	-d | --delete Remove the original files after the conversion process is finished"
	echo "	-f | --folder Assign a folder to save converted files"
	echo "	-r | --replace Replace old files by converted files"
	echo "	-o | --only	Keep the original files, depends on replace mode enable"
	echo "	-h | --help	Help"
}

while [[ "$1" != "" ]]; do
	case $1 in
		-d | --delete )
			delete=1
			shift
			;;
		-f | --folder )
			folder=1
			shift
			
			directory="$1"
			if [ -d "$directory" ]
			then
			   echo "Directory not found."
			else
			   echo "Directory is not assigned or not found ($directory)"
			   exit 1
			fi
			shift
			;;
		-r | --replace )
			replace=1
			shift
			;;
		-o | --only )
			only=1
			shift
			;;
		-h | --help )
			shift
			_help
			exit
			;;
		* )
			echo "Command '$1' unprocessable"
			exit 
			;;
	esac
done

if [[ $folder = 0 ]]; then
	mkdir "$directory" || exit $?
fi

echo "#### Conversion started...   ####"

for file in "$current"/*; do

   	if [ "${file##*.}" = "mp3" -o "${file##*.}" = "wav" -o "${file##*.}" = "MP3" ]; then
      
		name=`echo "$file" | sed -e "s/.*\///"`
		name=`echo "$name" | sed -e "s/.mp3$//g"`
		name=`echo "$name" | sed -e "s/.wav$//g"`
		name=`echo "$name" | sed -e "s/.MP3$//g"`

		echo "---------------------------------------------------------------------"
		echo "INPUT: $file"
		echo "OUTPUT: $directory/$name.mp3"
		echo "Waiting..."
        ffmpeg -loglevel panic -i "$file" -vn -ar 44100 -ac 2 -ab 128k -f mp3 "$directory/$name.mp3"
   		
   		status=$?
   		if [[ $status = 0 ]]; then 
   			if [[ $delete = 1 || $replace = 1 ]]; then
	   			rm "$file"
	   			if [[ $replace = 1 ]]; then
	   				cp "$directory/$name.mp3" "$current/$name.mp3"
	   			fi
   			fi
   			echo "Finished"
   		else
   			echo "There an error to convert '$name.mp3'."
   		fi

   	fi

done

echo "---------------------------------------------------------------------"

if [[ $replace = 1 && $only = 1 ]]; then
	rm -rf "$directory"
fi

echo "####   All finished   ####"
exit
